### ISSUE TITLE
Line break css when printing CSVs

### ISSUE THREAD

**Issue by willfulbard** [camphoric/camphoric#406]
Need a good way to print, also:

```css
@media print {
  div.camper {
      break-inside: avoid;
  }
}

```
